<?php defined("MOODLE_INTERNAL") || die(); ?>
<hr />

<div class="container-fluid-dashboard">
    <div class="row">
        <nav class="col-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span><?= get_string('navtitlepersonal', 'report_clearview') ?></span>
                </h6>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link <?= $reporttype === 1 ? 'active' : ''; ?>" href="/report/clearview/index.php?rpt=<?=REPORT_TYPE_PERSONAL ?>">
                            <span data-feather="folder"></span>
                            <?= $reporttypenamesarray[REPORT_TYPE_PERSONAL] ?>
                        </a>
                    </li>
                </ul>
                <?php if ($iscategorymanager): ?>
                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span><?= get_string('navtitlecatmanager', 'report_clearview') ?></span>
                </h6>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link <?= $reporttype === 2 ? 'active' : ''; ?>" href="/report/clearview/index.php?rpt=<?=REPORT_TYPE_COURSE ?>&id=<?=$categoryid ?>">
                            <span data-feather="grid"></span>
                            <?= $reporttypenamesarray[REPORT_TYPE_COURSE] ?>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link <?= $reporttype === 3 ? 'active' : ''; ?>" href="/report/clearview/index.php?rpt=<?=REPORT_TYPE_USER ?>&id=<?=$categoryid ?>">
                            <span data-feather="users"></span>
                            <?= $reporttypenamesarray[REPORT_TYPE_USER] ?>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" target="_blank" href="/report/lpmonitoring/index.php?pagecontextid=<?= $contextid ?>">
                            <span data-feather="layers"></span>
                            <?= get_string('statslearningplan', 'report_lpmonitoring') ?>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" target="_blank" href="/enrol/programs/management/index.php?contextid=<?=$contextid ?>">
                            <span data-feather="git-branch"></span>
                            <?= get_string('programs', 'enrol_programs') ?>
                        </a>
                    </li>
                </ul>
                <?php endif; ?>

                <?php if ($iscategorymanager): ?>
                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span><?= get_string('navtitlefavlinks', 'report_clearview') ?></span>
                </h6>
                <ul class="nav flex-column mb-2">
                    <li class="nav-item">
                        <a class="nav-link" target="_blank" href="/blocks/configurable_reports/managereport.php?courseid=1">
                            <span data-feather="file-text"></span>
                            <?= get_string('blockname', 'block_configurable_reports') ?>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" target="_blank" href="/reportbuilder/index.php">
                            <span data-feather="file-text"></span>
                            <?= get_string('reportbuilder', 'core_reportbuilder') ?>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link d-flex align-items-center" href="#">
                            <span data-feather="file-text"></span>
                            <?= get_string('navtitlefavorites', 'report_clearview') ?>
                            <span class="m-2" data-feather="plus-circle"></span>
                        </a>
                    </li>
                </ul>
                <?php endif; ?>
            </div>
        </nav>

        <main role="main" class="col-md-9 col-lg-10 ml-sm-auto pt-3 px-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
                <h1 class="h2"><?=$reporttypename ?><br /><span class="lead"><?= get_string('navtitledashboard', 'report_clearview') ?></span></h1>
            </div>

            <div class="row">
                <div class="col-sm-3 col-md-4 col-lg-5 ml-4 mr-4 p-4">
                    <canvas class="my-4" id="myChartTarget1"></canvas>
                </div>
                <div class="col-sm-4 col-md-5 col-lg-6 mt-5 ml-4 mx-1 p-1 align-items-center">
                    <!-- <canvas class="my-4" id="myChartTarget2"></canvas>
                    <canvas class="my-4" id="myChartTarget3"></canvas> -->
                    <div class="display-4 mt-5 text-center"><?= get_string('tablenumberofcourses', 'report_clearview') ?></div>
                    <div class="display-1 mt-5 text-center"><strong><?= count($userenrolledcourses['courses']) ?></strong></div>
                </div>
            </div>

            <div class="row m-2 p-2">
                <div class="col-sm-8">
                    <h2><?= get_string('tabletitlemycourses', 'report_clearview') ?></h2>
                </div>
                <div class="col-sm-4">
                </div>
            </div>

            <div class="table-responsive">
                <table id="data-table-1" class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th><?= get_string('tableid', 'report_clearview') ?></th>
                            <th><?= get_string('tabletitle', 'report_clearview') ?></th>
                            <th class="text-center"><?= get_string('tablestartdate', 'report_clearview') ?></th>
                            <th class="text-center"><?= get_string('tablecompletionrate', 'report_clearview') ?></th>
                            <th class="text-center"><?= get_string('tabledetails', 'report_clearview') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($userenrolledcourses['courses'] as $courseobject): ?>
                        <tr>
                            <td class="text-center"><?=$courseobject['course_info']['idnumber'] ?: 'N/A' ?></td>
                            <td><?=$courseobject['course_info']['fullname'] ?></td>
                            <td class="text-center"><?=gmdate("Y-m-d H:i", $courseobject['course_info']['startdate']) ?: 0 ?></td>
                            <td class="text-center"><?=$courseobject['completion'] ?: 0 ?> %</td>
                            <td class="text-center"><a target="_blank" href="/grade/report/user/index.php?id=<?=$courseobject['course_info']['id'] ?>"><span class="text-success" data-feather="file-text"></span></a></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </main>
    </div>
</div>

<script>
    const categorycompletion = <?= json_encode($userenrolledcourses['course_completion_average']) ?>;

    const stringtranslations = <?= json_encode([
            'jscurrentlocale' => current_language(),
            'jsbaseurlfr' => (new moodle_url('/report/clearview/js/DataTables/fr-FR.json'))->out(),
            'jscompletiongraphtitle' => get_string('jscompletiongraphtitle', 'report_clearview'),
            'jscompletiongraphcomplete' => get_string('jscompletiongraphcomplete', 'report_clearview'),
            'jscompletiongraphincomplete' => get_string('jscompletiongraphincomplete', 'report_clearview'),
            'jscompletiongraphinpercentage' => get_string('jscompletiongraphinpercentage', 'report_clearview'),
    ]) ?>;
</script>